---
---

<center><h1> 📍 📍 Basics of NumPy 📍 📍 </h1></center>


NumPy is the fundamental package for scientific computing with Python. It contains among other things:
 
 - A powerful N-dimensional array object
 - Sophisticated (broadcasting) functions
 - Tools for integrating C/C++ and Fortran code
 - Useful linear algebra, Fourier transform, and random number capabilities

***Source:*** https://numpy.org/

---

In [76]:
# importing the numpy library
import numpy as np

***If you got an error while running the above cell, import it by using the following command***


***`!pip3 install numpy`***

---

In [77]:
# check verison of the numpy library
np.__version__

'1.17.1'

In [78]:
# create a numpy array
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [79]:
[1,4,'2',5,False]

[1, 4, '2', 5, False]

***Difference between numpy array and list***

- Data type should be same of all the elements in a numpy array whereas it can be different in case of lists.
- **Broadcasting:** https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

---

In [80]:
# if we add an element of string data type in a numpy array
# then it will upcast the data type to string of all the elements.
np.array([1, 4, 2, '5', 3, False])

array(['1', '4', '2', '5', '3', 'False'], dtype='<U21')

***Now, we will create one sample list and numpy array and apply a very basic function of multiplication by 2. We will see that in case of list the elements are duplicated and appended to the list whereas in case of numpy array we got an array where all elements are multiplied by 2.***

----

In [81]:
# create a sample list
sample_list = [1, 2, 3, 4, 5, 6]

In [82]:
sample_list*2 

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [83]:
# create a sample numpy array
sample_numpy_array = np.array([1, 2, 3, 4, 5, 6])

In [84]:
sample_numpy_array+2

array([3, 4, 5, 6, 7, 8])

---

***Create a matrix using numpy***

---

In [85]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

In [86]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [87]:
# MATRIX
a = np.array(a)

In [88]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
a[0][1]

2

In [90]:
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[4, 7, 6],
       [8, 8, 1],
       [6, 7, 7]])

In [92]:
# create another matrix
np.random.randint(0, 10, (3, 3))

array([[8, 1, 5],
       [9, 8, 9],
       [4, 3, 0]])

***We got a different matrix when we generated another random matrix: We can get the same matrix again by fixing the seed. Let's see how?***


---

In [93]:
# fixing the random seed
np.random.seed(0)
np.random.randint(0, 10, (3, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [94]:
# fixing the random seed
np.random.seed(0)
np.random.randint(0, 10, (3, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

***Create a matrix of `Zeros` of specific dimension.***


---

In [95]:
# Create a 2 X 10 integer array filled with zeros
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [96]:
# Create a 4 X 5 integer array filled with zeros
np.zeros((4,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

***Create a matrix of `Ones` of specific dimension.***

---

In [97]:
# Create a 2 X 10 integer array filled with ones
np.ones((2,10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [98]:
# Create a 4 X 5 integer array filled with ones
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [99]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

***Create a matrix of filled with any specific number of specific dimension.***

---

In [100]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [101]:
# Create a 2x4 array filled with 7
np.full((2, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])



---
***Array Concatenation :***


---



In [102]:
# concatenating 2-D arrays
matrix1 = np.array([[1, 2, 3], 
                    [4, 5, 6]])
print("matrix 1")
matrix1

matrix 1


array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
matrix2 = np.array([[7, 8, 9], 
                    [10, 11, 12]])
print("matrix 2",)
matrix2

matrix 2


array([[ 7,  8,  9],
       [10, 11, 12]])

***Concatenate Row wise***

---

In [104]:
# concatenate along the first axis
matrix_1_2_combineRowwise = np.concatenate([matrix1, matrix2],axis=0)
print("Combined on Row (axis=0)")
matrix_1_2_combineRowwise

Combined on Row (axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

***Concatenate Column wise***


---

In [105]:
# concatenate along the second axis (zero-indexed)
matrix_1_2_combineColwise = np.concatenate([matrix1, matrix2], axis=1)
print("Combined on Col (axis=1)")
matrix_1_2_combineColwise

Combined on Col (axis=1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

***Learn more about the numpy here: https://numpy.org/doc/1.17/user/index.html***

---